const CATEGORIES = [
  {
    value: "Automotive",
    children: [
      {
        value: "Auto Body Styles",
        children: [
          { value: "Commercial Trucks" },
          { value: "Convertible" },
          { value: "Coupe" },
          { value: "Crossover" },
          { value: "Hatchback" },
          { value: "Microcar" },
          { value: "Minivan" },
          { value: "Off-Road Vehicles" },
          { value: "Pickup Trucks" },
          { value: "SUV" },
          { value: "Sedan" },
          { value: "Van" },
        ],
      },
      { value: "Auto Buying and Selling" },
      { value: "Auto Insurance" },
      { value: "Auto Parts" },
      { value: "Auto Recalls" },
      { value: "Auto Rentals" },
      { value: "Auto Repair" },
      { value: "Auto Safety" },
      { value: "Auto Shows" },
      {
        value: "Auto Type",
        children: [
          { value: "Budget Cars" },
          { value: "Certified Pre-Owned Cars" },
          { value: "Classic Cars" },
          { value: "Concept Cars" },
          { value: "Driverless Cars" },
          { value: "Green Vehicles" },
          { value: "Luxury Cars" },
          { value: "Performance Cars" },
        ],
      },
      { value: "Car Culture" },
      { value: "Motorcycles" },
      { value: "Scooters" },
    ],
  },
  {
    value: "Careers",
    children: [
      { value: "Apprenticeships" },
      { value: "Career Advice" },
      { value: "Career Planning" },
      { value: "Job Search" },
      { value: "Remote Working" },
      { value: "Vocational Training" },
    ],
  },
  {
    value: "Education",
    children: [
      { value: "Adult Education" },
      { value: "College Education" },
      { value: "Early Childhood Education" },
      { value: "Educational Assessment" },
      { value: "Homeschooling" },
      { value: "Homework and Study" },
      { value: "Language Learning" },
      { value: "Online Education" },
      { value: "Primary Education" },
      { value: "Private School" },
      { value: "Secondary Education" },
      { value: "Special Education" },
    ],
  },
  {
    value: "Events and Attractions",
    children: [
      { value: "Amusement and Theme Parks" },
      { value: "Bars & Restaurants" },
      { value: "Business Expos & Conferences" },
      { value: "Casinos & Gambling" },
      { value: "Comedy Events" },
      { value: "Concerts & Music Events" },
      { value: "Historic Site and Landmark Tours" },
      { value: "Museums & Galleries" },
      { value: "Musicals" },
      { value: "National & Civic Holidays" },
      { value: "Nightclubs" },
      { value: "Outdoor Activities" },
      { value: "Parks & Nature" },
      { value: "Party Supplies and Decorations" },
      {
        value: "Personal Celebrations & Life Events",
        children: [{ value: "Funeral" }],
      },
      { value: "Zoos & Aquariums" },
    ],
  },
  {
    value: "Family and Relationships",
    children: [
      { value: "Bereavement" },
      { value: "Dating" },
      { value: "Divorce" },
      { value: "Eldercare" },
      { value: "Marriage and Civil Unions" },
      { value: "Parenting" },
    ],
  },
  {
    value: "Fine Art",
    children: [
      { value: "Digital Arts" },
      { value: "Modern Art" },
      { value: "Opera" },
      { value: "Theater" },
    ],
  },
  {
    value: "Food & Drink",
    children: [
      { value: "Alcoholic Beverages" },
      { value: "Barbecues and Grilling" },
      { value: "Cooking" },
      { value: "Desserts and Baking" },
      { value: "Dining Out" },
      { value: "Food Allergies" },
      { value: "Healthy Cooking and Eating" },
      { value: "Non-Alcoholic Beverages" },
      { value: "Vegan Diets" },
      { value: "Vegetarian Diets" },
    ],
  },
  {
    value: "Healthy Living",
    children: [
      { value: "Children's Health" },
      { value: "Fitness and Exercise" },
      { value: "Men's Health" },
      { value: "Nutrition" },
      { value: "Senior Health" },
      { value: "Weight Loss" },
      { value: "Wellness" },
      { value: "Women's Health" },
    ],
  },
  {
    value: "Hobbies & Interests",
    children: [
      { value: "Antiquing and Antiques" },
      { value: "Arts and Crafts" },
      { value: "Beekeeping" },
      { value: "Birdwatching" },
      { value: "Cigars" },
      { value: "Musical Instruments" },
      { value: "Paranormal Phenomena" },
    ],
  },
  {
    value: "Home & Garden",
    children: [
      { value: "Gardening" },
      { value: "Home Appliances" },
      { value: "Home Improvement" },
      { value: "Home Security" },
      { value: "Interior Decorating" },
      { value: "Landscaping" },
      { value: "Outdoor Decorating" },
      { value: "Remodeling & Construction" },
      { value: "Smart Home" },
    ],
  },
  {
    value: "Medical Health",
    children: [
      { value: "Cosmetic Medical Services" },
      {
        value: "Diseases and Conditions",
        children: [
          { value: "Allergies" },
          { value: "Blood Disorders" },
          { value: "Bone and Joint Conditions" },
          { value: "Brain and Nervous System Disorders" },
          { value: "Cancer" },
          { value: "Cold and Flu" },
          { value: "Dental Health" },
          { value: "Diabetes" },
          { value: "Digestive Disorders" },
          { value: "Ear, Nose and Throat Conditions" },
          {
            value: "Endocrine and Metabolic Diseases",
            children: [
              { value: "Hormonal Disorders" },
              { value: "Menopause" },
              { value: "Thyroid Disorders" },
            ],
          },
          { value: "Eye and Vision Conditions" },
          { value: "Foot Health" },
          { value: "Heart and Cardiovascular Diseases" },
          { value: "Infectious Diseases" },
          { value: "Injuries", children: [{ value: "First Aid" }] },
          { value: "Lung and Respiratory Health" },
          { value: "Mental Health" },
          {
            value: "Reproductive Health",
            children: [
              { value: "Birth Control" },
              { value: "Infertility" },
              { value: "Pregnancy" },
            ],
          },
          {
            value: "Sexual Health",
            children: [{ value: "Sexual Conditions" }],
          },
          { value: "Skin and Dermatology" },
          { value: "Sleep Disorders" },
          { value: "Substance Abuse" },
        ],
      },
      { value: "Medical Tests" },
      { value: "Pharmaceutical Drugs" },
      { value: "Surgery" },
      { value: "Vaccines" },
    ],
  },
  { value: "Movies" },
  { value: "Music and Audio" },
  {
    value: "News and Politics",
    children: [
      { value: "Crime" },
      { value: "Disasters" },
      { value: "Law" },
      { value: "Local News" },
      {
        value: "Politics",
        children: [
          { value: "Elections" },
          { value: "Political Issues" },
          { value: "War and Conflicts" },
        ],
      },
      { value: "Weather" },
    ],
  },
  {
    value: "Personal Finance",
    children: [
      { value: "Financial Assistance" },
      { value: "Financial Planning" },
      { value: "Frugal Living" },
      { value: "Insurance" },
      { value: "Personal Investing" },
      { value: "Retirement Planning" },
    ],
  },
  {
    value: "Books and Literature",
    children: [
      { value: "Biographies" },
      { value: "Comics and Graphic Novels" },
      { value: "Cookbooks" },
      { value: "Poetry" },
    ],
  },
  {
    value: "Pets",
    children: [
      { value: "Birds" },
      { value: "Cats" },
      { value: "Dogs" },
      { value: "Pet Adoptions" },
      { value: "Pet Supplies" },
      { value: "Reptiles" },
      { value: "Veterinary Medicine" },
    ],
  },
  {
    value: "Pop Culture",
    children: [
      { value: "Celebrity Deaths" },
      { value: "Celebrity Homes" },
      { value: "Celebrity Relationships" },
      { value: "Celebrity Style" },
      { value: "Humor and Satire" },
    ],
  },
  { value: "Real Estate" },
  {
    value: "Religion & Spirituality",
    children: [
      { value: "Astrology" },
      { value: "Atheism" },
      { value: "Buddhism" },
      { value: "Christianity" },
      { value: "Hinduism" },
      { value: "Islam" },
      { value: "Judaism" },
      { value: "Sikhism" },
      { value: "Spirituality" },
    ],
  },
  {
    value: "Science",
    children: [
      { value: "Biological Sciences" },
      { value: "Chemistry" },
      { value: "Environment" },
      { value: "Genetics" },
      { value: "Geography" },
      { value: "Geology" },
      { value: "Physics" },
      { value: "Space and Astronomy" },
    ],
  },
  {
    value: "Shopping",
    children: [
      { value: "Coupons and Discounts" },
      { value: "Flower Shopping" },
      { value: "Gifts and Greetings Cards" },
      { value: "Grocery Shopping" },
      { value: "Holiday Shopping" },
      { value: "Sales and Promotions" },
    ],
  },

  {
    value: "Sports",
    children: [
      { value: "American Football" },
      { value: "Australian Rules Football" },
      { value: "Auto Racing" },
      { value: "Badminton" },
      { value: "Baseball" },
      { value: "Basketball" },
      { value: "Beach Volleyball" },
      { value: "Bodybuilding" },
      { value: "Bowling" },
      { value: "Boxing" },
      { value: "Cheerleading" },
      {
        value: "College Sports",
        children: [
          { value: "College Baseball" },
          { value: "College Basketball" },
          { value: "College Football" },
        ],
      },

      { value: "Cricket" },
      { value: "Cycling" },
      { value: "Darts" },
      { value: "Disabled Sports" },
      { value: "Diving" },
      {
        value: "Extreme Sports",
        children: [
          { value: "Canoeing and Kayaking" },
          { value: "Climbing" },
          { value: "Paintball" },
          { value: "Scuba Diving" },
          { value: "Skateboarding" },
          { value: "Snowboarding" },
          { value: "Surfing and Bodyboarding" },
        ],
      },

      { value: "Fantasy Sports" },
      { value: "Field Hockey" },
      { value: "Figure Skating" },
      { value: "Fishing Sports" },
      { value: "Golf" },
      { value: "Gymnastics" },
      { value: "Horse Racing" },
      { value: "Ice Hockey" },
      { value: "Lacrosse" },
      { value: "Martial Arts" },
      {
        value: "Olympic Sports",
        children: [
          { value: "Summer Olympic Sports" },
          { value: "Winter Olympic Sports" },
        ],
      },

      { value: "Poker and Professional Gambling" },
      { value: "Rodeo" },
      { value: "Rowing" },
      { value: "Rugby" },
      { value: "Sailing" },
      { value: "Skiing" },
      { value: "Snooker/Pool/Billiards" },
      { value: "Soccer" },
      { value: "Softball" },
      { value: "Sports Equipment" },
      { value: "Swimming" },
      { value: "Table Tennis" },
      { value: "Tennis" },
      { value: "Track and Field" },
      { value: "Volleyball" },
      { value: "Walking" },
      { value: "Water Polo" },
      { value: "Weightlifting" },
      { value: "Wrestling" },
    ],
  },

  {
    value: "Business and Finance",
    children: [
      {
        value: "Business",
        children: [
          { value: "Awards" },
          { value: "Business Accounting & Finance" },
          { value: "Business Administration" },
          {
            value: "Business Banking & Finance",
            children: [
              { value: "Acquisitions, Mergers and Takeovers" },
              { value: "Angel Investment" },
              { value: "Bankruptcy" },
              { value: "Business Loans" },
              { value: "Debt Factoring & Invoice Discounting" },
              { value: "Private Equity" },
              { value: "Sale & Lease Back" },
              { value: "Venture Capital" },
            ],
          },
          { value: "Business I.T." },
          { value: "Business Operations" },
          { value: "Business Utilities" },
          {
            value: "Consumer Issues",
            children: [{ value: "Recalls" }],
          },
          { value: "Contracts and Agreements" },
          { value: "Environmental, Social and Governance (ESG)" },
          { value: "Executive Leadership & Management" },
          { value: "Funding" },
          { value: "Government Business" },
          { value: "Green Solutions" },
          { value: "Human Resources" },
          { value: "Intellectual Property" },
          { value: "Large Business" },
          { value: "Litigation" },
          { value: "Logistics" },
          { value: "Marketing and Advertising" },
          { value: "Partnerships and Joint Ventures" },
          {
            value: "Personnel Changes",
            children: [{ value: "Key Hires" }, { value: "Layoffs" }],
          },

          { value: "Products and Services Announcements" },
          { value: "Real Estate Transactions" },
          {
            value: "Regulatory Approvals",
            children: [{ value: "Investigational New Drug Application" }],
          },
          { value: "Sales" },
          { value: "Small and Medium-sized Business" },
          { value: "Startups" },
          { value: "Stock Offerings and IPOs" },
          {
            value: "Stock Price News",
            children: [
              { value: "Dividends" },
              { value: "Investment Opinion" },
              { value: "Sales and Earnings" },
              { value: "Stock Split" },
            ],
          },
        ],
      },
      {
        value: "Economy",
        children: [
          { value: "Commodities" },
          { value: "Currencies" },
          { value: "Financial Crisis" },
          { value: "Financial Reform" },
          { value: "Financial Regulation" },
          { value: "Gasoline Prices" },
          { value: "Housing Market" },
          { value: "Interest Rates" },
          { value: "Job Market" },
        ],
      },

      {
        value: "Industries",
        children: [
          { value: "Advertising Industry" },
          { value: "Agriculture" },
          { value: "Apparel Industry" },
          { value: "Automotive Industry" },
          { value: "Aviation Industry" },
          { value: "Biotech and Biomedical Industry" },
          { value: "Civil Engineering Industry" },
          { value: "Construction Industry" },
          { value: "Defense Industry" },
          { value: "Education industry" },
          { value: "Entertainment Industry" },
          { value: "Environmental Services Industry" },
          { value: "Financial Industry" },
          { value: "Food Industry" },
          { value: "Healthcare Industry" },
          { value: "Hospitality Industry" },
          { value: "Information Services Industry" },
          { value: "Legal Services Industry" },
          { value: "Logistics and Transportation Industry" },
          { value: "Management Consulting Industry" },
          { value: "Manufacturing Industry" },
          { value: "Mechanical and Industrial Engineering Industry" },
          { value: "Media Industry" },
          { value: "Metals Industry" },
          { value: "Non-Profit Organizations" },
          { value: "Pharmaceutical Industry" },
          { value: "Power and Energy Industry" },
          { value: "Publishing Industry" },
          { value: "Real Estate Industry" },
          { value: "Retail Industry" },
          { value: "Technology Industry" },
          { value: "Telecommunications Industry" },
        ],
      },
    ],
  },

  {
    value: "Style & Fashion",
    children: [
      { value: "Beauty" },
      { value: "Body Art" },
      { value: "Fashion Trends" },
      { value: "Men's Fashion" },
      { value: "Women's Fashion" },
    ],
  },

  {
    value: "Technology & Computing",
    children: [
      { value: "Artificial Intelligence" },
      { value: "Augmented Reality" },
      {
        value: "Computing",
        children: [
          { value: "Computer Networking" },
          { value: "Computer Peripherals" },
          { value: "Computer Software and Applications" },
          { value: "3-D Graphics" },
          { value: "Antivirus Software" },
          { value: "Browsers" },
          { value: "Computer Animation" },
          { value: "Databases" },
          { value: "Desktop Publishing" },
          { value: "Digital Audio" },
          { value: "Graphics Software" },
          { value: "Operating Systems" },
          { value: "Photo Editing Software" },
          { value: "Shareware and Freeware" },
          { value: "Video Software" },
          { value: "Web Conferencing" },
          { value: "Data Storage and Warehousing" },
          { value: "Desktops" },
          { value: "Information and Network Security" },
          { value: "Internet" },
          { value: "Cloud Computing" },
          { value: "Email" },
          { value: "IT and Internet Support" },
          { value: "Internet for Beginners" },
          { value: "Internet of Things" },
          { value: "Search" },
          { value: "Social Networking" },
          { value: "Web Design and HTML" },
          { value: "Web Development" },
          { value: "Web Hosting" },
          { value: "Laptops" },
          { value: "Programming Languages" },
          { value: "Technical Documentation" },
        ],
      },
      {
        value: "Consumer Electronics",
        children: [
          { value: "Cameras and Camcorders" },
          { value: "Home Entertainment Systems" },
          { value: "Smartphones" },
          { value: "Tablets and E-readers" },
          { value: "Wearable Technology" },
        ],
      },
      { value: "Robotics" },
      { value: "Virtual Reality" },
    ],
  },

  { value: "Television" },
  {
    value: "Travel",
    children: [
      {
        value: "Travel Locations",
        children: [
          { value: "Africa Travel" },
          { value: "Asia Travel" },
          { value: "Australia and Oceania Travel" },
          { value: "Europe Travel" },
          { value: "North America Travel" },
          { value: "Polar Travel" },
          { value: "South America Travel" },
        ],
      },
      { value: "Travel Preparation and Advice" },
      {
        value: "Travel Type",
        children: [
          { value: "Adventure Travel" },
          { value: "Air Travel" },
          { value: "Beach Travel" },
          { value: "Budget Travel" },
          { value: "Business Travel" },
          { value: "Camping" },
          { value: "Cruises" },
          { value: "Day Trips" },
          { value: "Family Travel" },
          { value: "Honeymoons and Getaways" },
          { value: "Hotels and Motels" },
          { value: "Rail Travel" },
          { value: "Road Trips" },
          { value: "Spas" },
        ],
      },
    ],
  },
  {
    value: "Video Gaming",
    chilrden: [
      { value: "Console Games" },
      { value: "Mobile Games" },
      { value: "PC Games" },
      { value: "eSports" },
    ],
  },
];

export { CATEGORIES };
